apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      nodeSelector:
        'kubernetes.io/os': linux
      containers:
        - name: {{ .Values.appName }}
          image: {{ .Values.imageRegistry }}/{{ .Values.appName }}:{{ .Values.apiDockerTag }}
          imagePullPolicy: Always
          resources:
            limits:
              memory: '512Mi'
              cpu: '100m'
          # volumeMounts:
          #   - name: config-file-sec
          #     mountPath: '/usr/src/config/'
          ports:
            - containerPort: {{ .Values.PORT }}
          # Add in this lifecycle command to create a symlink to the config
          # file in src/utils/config.json
      #     lifecycle:
      #       postStart:
      #         exec:
      #           command:
      #             - /bin/sh
      #             - -c
      #             - rm -rf ./src/config.json && ln -s /usr/src/config/config-sec.json ./src/config.json
      # volumes:
      #   - name: config-file-sec
      #     secret:
      #       secretName: config-sec.json
