imageRegistry: "muaksacheminhdevregistry.azurecr.io"
apiDockerTag: "1.7" # need to match package.json version
namespace: "muaksa"
PORT: 4000
environment: dev
ciNumber: CI00000000000 # sample CI number
appCiNumber: CI00000000000 # sample CI number
