module.exports = {
  provinces_territories: [
    {
      id: "0",
      name: "TEST",
      postal_abbrevation: "ON",
      capital: "Toronto",
      population: "14,734,014",
    },
    {
      id: "1",
      name: "Ontario",
      postal_abbrevation: "ON",
      capital: "Toronto",
      population: "14,734,014",
    },
    {
      id: "2",
      name: "Quebec",
      postal_abbrevation: "QC",
      capital: "Quebec City",
      population: "8,574,571",
    },
    {
      id: "3",
      name: "British Columbia",
      postal_abbrevation: "BC",
      capital: "Victoria",
      population: "5,147,712",
    },
    {
      id: "4",
      name: "Alberta",
      postal_abbrevation: "AB",
      capital: "Edmonton",
      population: "4,421,876",
    },
    {
      id: "5",
      name: "Manitoba",
      postal_abbrevation: "MB",
      capital: "Winnipeg",
      population: "1,379,263",
    },
    {
      id: "6",
      name: "Saskatchewan",
      postal_abbrevation: "SK",
      capital: "Regina",
      population: "1,178,681",
    },
    {
      id: "7",
      name: "Nova Scotia",
      postal_abbrevation: "NS",
      capital: "Halifax",
      population: "979,351",
    },
    {
      id: "8",
      name: "New Brunswick",
      postal_abbrevation: "NB",
      capital: "Fredericton",
      population: "781,476",
    },
    {
      id: "9",
      name: "Newfoundland and Labrador",
      postal_abbrevation: "NL",
      capital: "St. John's",
      population: "522,103",
    },
    {
      id: "10",
      name: "Prince Edward Island",
      postal_abbrevation: "PE",
      capital: "Charlottetown",
      population: "159,625",
    },
    {
      id: "11",
      name: "Northwest Territories",
      postal_abbrevation: "NT",
      capital: "Yellowknife",
      population: "45,161",
    },
    {
      id: "12",
      name: "Yukon",
      postal_abbrevation: "YT",
      capital: "	Whitehorse",
      population: "42,052",
    },
    {
      id: "13",
      name: "Nunavut",
      postal_abbrevation: "NU",
      capital: "Iqaluit",
      population: "39,353",
    },
  ],
};
